spring:
  kafka:
    topic:
      error-log: error-logs
      info-log: info-logs

    # Connect to the Kafka container (named 'kafka') on port 9092
    bootstrap-servers: kafka:9092
    consumer:
      group-id: group1
      max-partition-fetch-bytes: 200000000
    producer:
      max-request-size: 200000000
    properties:
      max.request.size: 200000000
      message.max.bytes: 200000000
      fetch.message.max.bytes: 200000000

  application:
    name: task-management-service

  datasource:
    url: jdbc:postgresql://postgres-task-management-service:5432/definex_task_management_service_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

server:
  port: 8081

swagger:
  api:
    title: Task Management API
    description: API documentation for managing tasks, projects, departments, and comments.
    version: 1.0.0
