server:
  port: 8082

spring:
  application:
    name: file-storage-service

  datasource:
    url: "jdbc:postgresql://file-storage-db-host:5432/definex_file_storage_service_db"
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

eureka:
  client:
    serviceUrl:
      defaultZone: "http://eureka-server-host:8761/eureka"
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
