server:
  port: 8083

spring:
  application:
    name: user-authentication-service

  datasource:
    # Replace 'user-auth-db-host' with your alias for the Postgres container
    url: "jdbc:postgresql://user-auth-db-host:5432/definex_user_authentication_service_db"
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true

application:
  security:
    jwt:
      secret-key: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
      expiration: 86400000
      refresh-token:
        expiration: 604800000

eureka:
  client:
    serviceUrl:
      defaultZone: "http://eureka-server-host:8761/eureka"
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
